openapi: 3.0.2
info:
  title: "转储服务"
  description: |

  version: v1
servers:
  - url: https://app-gateway.realsee.com
paths:
  /open/v1/shepherd/task/create:
    post:
      summary: 异步任务创建
      description: |
        #### 支持的离线任务
        |名称|描述|备注|
        |-|-|-|
        |vr_compress|触发指定VR编码的转存打包离线任务，当任务完成之后会回调至配置的`ENDPOINT`之上|-|

      parameters:
        - name: Authorization
          in: header
          description: 鉴权获取的access_token
          required: true
          schema:
            type: string
            default: your_access_token

      requestBody:
        content:
          "application/json":
            schema:
              type: object
              required: ["task_type", "vr_code"]
              properties:
                vr_code:
                  description: "VR 编码"
                  type: string
                  default: "80drj5DRZejY2Dq8Oe"
                task_type:
                  description: "任务类型: `vr_compress` - 转存打包"
                  type: string
                  enum: ["vr_compress"]
      responses:
        200:
          description: V1ShepherdTaskCreate
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: string
                    description: "标识唯一一次请求"
                  trace_id:
                    type: string
                    description: "标识唯一一次请求, 同 request_id 类似，但主要用于请求追溯的场景"
                  code:
                    type: integer
                    description: "错误码，请求成功时默认为 0"
                  status:
                    type: string
                    description: "错误信息，请求成功是默认为 success"
                  cost:
                    type: integer
                    description: "服务端计算耗时，单位 ms"
                  data:
                    type: integer
                    description: "任务TaskID，用于后续追查执行计划、日志等信息"

components:
  securitySchemes:
    api_key:
      type: http
      scheme: bearer
      bearerFormat: jwt
